USE DRONE_DIY

ALTER TABLE 문의
ADD CONSTRAINT 문의FK FOREIGN KEY (회원ID) REFERENCES 회원(회원ID);

ALTER TABLE 답변댓글
ADD CONSTRAINT  답변FK1 FOREIGN KEY (문의번호) REFERENCES 문의(문의번호)

ALTER TABLE 답변댓글
ADD CONSTRAINT  답변FK2 FOREIGN KEY (직원번호) REFERENCES 직원(직원번호)

ALTER TABLE 부품업체
ADD CONSTRAINT 업체FK FOREIGN KEY (직원번호) REFERENCES 직원(직원번호)

ALTER TABLE 공급
ADD CONSTRAINT 공급FK1 FOREIGN KEY (부품번호) REFERENCES 부품(부품번호)

ALTER TABLE 공급
ADD CONSTRAINT 공급FK2 FOREIGN KEY (업체번호) REFERENCES 부품업체(업체번호)

ALTER TABLE 프레임
ADD CONSTRAINT 프레임FK FOREIGN KEY (부품번호) REFERENCES 부품(부품번호)

ALTER TABLE 프로펠러
ADD CONSTRAINT 프로펠러FK FOREIGN KEY (부품번호) REFERENCES 부품(부품번호)

ALTER TABLE 모터
ADD CONSTRAINT 모터FK FOREIGN KEY (부품번호) REFERENCES 부품(부품번호)

ALTER TABLE 배터리
ADD CONSTRAINT 배터리FK FOREIGN KEY (부품번호) REFERENCES 부품(부품번호)

ALTER TABLE 카메라
ADD CONSTRAINT 카메라FK FOREIGN KEY (부품번호) REFERENCES 부품(부품번호)

ALTER TABLE 주문내역
ADD CONSTRAINT 주문FK FOREIGN KEY (회원ID) REFERENCES 회원(회원ID)

ALTER TABLE 포함
ADD CONSTRAINT 포함FK1 FOREIGN KEY (주문번호) REFERENCES 주문내역(주문번호)

ALTER TABLE 포함
ADD CONSTRAINT 포함FK2 FOREIGN KEY (부품번호) REFERENCES 부품(부품번호)

ALTER TABLE 신규부품
ADD CONSTRAINT 신규FK1 FOREIGN KEY (회원ID) REFERENCES 회원(회원ID)

ALTER TABLE 신규부품
ADD CONSTRAINT 신규FK2 FOREIGN KEY (직원번호) REFERENCES 직원(직원번호)